# Generated by Django 5.2.7 on 2025-11-24 05:57

import django.db.models.deletion
import usuario_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_e_data', models.DateTimeField()),
                ('origem', models.CharField(max_length=125)),
                ('destino', models.CharField(max_length=125)),
                ('vagas_disponiveis', models.IntegerField(validators=[usuario_app.validators.validar_capacidade])),
                ('status', models.CharField(choices=[('Agendada', 'Agendada'), ('Em Andamento', 'Em Andamento'), ('Finalizada', 'Finalizada'), ('Cancelada', 'Cancelada')], default='Agendada', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('Motorista', 'Motorista'), ('Passageiro', 'Passageiro')], max_length=50)),
                ('tipo_campus', models.CharField(choices=[('Campus Natal-Central', 'Campus Natal-Central'), ('Campus Mossoró', 'Campus Mossoró'), ('Campus Parnamirim', 'Campus Parnamirim'), ('Campus Pau dos Ferros', 'Campus Pau dos Ferros')], max_length=50)),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[usuario_app.validators.validar_cpf])),
                ('senha', models.CharField(max_length=255)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/')),
                ('is_motorista', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoCarona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Aceita', 'Aceita'), ('Recusada', 'Recusada')], default='Pendente', max_length=20)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('carona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario_app.carona')),
            ],
        ),
        migrations.AddField(
            model_name='carona',
            name='motorista',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carona_motorista', to='usuario_app.usuario'),
        ),
        migrations.AddField(
            model_name='carona',
            name='passageiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caronas_passageiro', to='usuario_app.usuario'),
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_veiculo', models.CharField(choices=[('Moto', 'Moto'), ('Carro', 'Carro')], max_length=50)),
                ('modelo', models.CharField(max_length=125)),
                ('marca', models.CharField(max_length=50)),
                ('ano', models.IntegerField(validators=[usuario_app.validators.validar_ano])),
                ('cor', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=7, unique=True)),
                ('capacidade', models.IntegerField(validators=[usuario_app.validators.validar_capacidade])),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario_app.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='carona',
            name='veiculo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuario_app.veiculo'),
        ),
    ]
