# Generated by Django 5.2.7 on 2026-01-07 02:05

import django.db.models.deletion
import django.utils.timezone
import usuario_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carona',
            name='passageiro',
        ),
        migrations.AddField(
            model_name='carona',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carona',
            name='motorista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caronas_como_motorista', to='usuario_app.usuario'),
        ),
        migrations.AlterField(
            model_name='carona',
            name='vagas_disponiveis',
            field=models.IntegerField(default=1, validators=[usuario_app.validators.validar_capacidade]),
        ),
        migrations.AlterField(
            model_name='carona',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caronas_veiculo', to='usuario_app.veiculo'),
        ),
        migrations.CreateModel(
            name='MensagemChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario_app.usuario')),
            ],
        ),
    ]
