# Generated by Django 5.2.7 on 2026-01-13 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_app', '0002_remove_carona_passageiro_carona_data_criacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaocarona',
            name='passageiro',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_caronas', to='usuario_app.usuario'),
        ),
        migrations.AlterField(
            model_name='solicitacaocarona',
            name='carona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='usuario_app.carona'),
        ),
        migrations.AlterUniqueTogether(
            name='solicitacaocarona',
            unique_together={('carona', 'passageiro')},
        ),
    ]
