# Generated by Django 5.2.7 on 2026-01-06 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_app', '0003_remove_carona_passageiro_carona_data_criacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaocarona',
            name='passageiro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuario_app.usuario'),
            preserve_default=False,
        ),
    ]
