# Generated by Django 5.2.7 on 2026-01-06 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_app', '0004_solicitacaocarona_passageiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaocarona',
            name='passageiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_passageiro', to='usuario_app.usuario'),
        ),
    ]
