# Generated by Django 5.2.7 on 2026-01-06 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_app', '0005_alter_solicitacaocarona_passageiro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacaocarona',
            name='passageiro',
        ),
    ]
