# Generated by Django 5.2.7 on 2026-01-10 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_app', '0007_solicitacaocarona_passageiro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('nova_solicitacao', 'Nova Solicitação de Carona'), ('solicitacao_aceita', 'Solicitação Aceita'), ('solicitacao_recusada', 'Solicitação Recusada'), ('passageiro_recusou', 'Passageiro Recusou Carona')], max_length=50)),
                ('mensagem', models.TextField()),
                ('lida', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('carona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='usuario_app.carona')),
                ('solicitacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='usuario_app.solicitacaocarona')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='usuario_app.usuario')),
            ],
        ),
    ]
