# Generated by Django 5.2.7 on 2026-01-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_app', '0008_notificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carona',
            name='status',
            field=models.CharField(choices=[('Agendada', 'Agendada'), ('Em Andamento', 'Em Andamento'), ('Finalizada', 'Finalizada'), ('Cancelada', 'Cancelada'), ('Removida', 'Removida')], default='Agendada', max_length=20),
        ),
    ]
