# Generated by Django 5.2.7 on 2026-01-14 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_app', '0009_alter_carona_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagemchat',
            name='carona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='usuario_app.carona'),
        ),
        migrations.AddField(
            model_name='mensagemchat',
            name='carona_ativa',
            field=models.BooleanField(default=True),
        ),
    ]
